urdf_nodes:
  - roslaunch gait1992_description fake_movement.launch use_gui:=${USE_GUI}
  - roslaunch gait1992_description generic_state_publisher_plus_custom_joints.launch base_parent:=$BASE_PARENT tf_prefix:=$TF_PREFIX  
  - roslaunch gait1992_description insoles_on_feet.launch foot_left_name:=$FOOT_LEFT_NAME foot_right_name:=$FOOT_RIGHT_NAME foot_distance_from_ground:=$FOOT_DISTANCE_FROM_GROUND tf_prefix:=$TF_PREFIX ignore_insole_imu_for_vis:=$IGNORE_INSOLE_IMU_FOR_VIS
  - roslaunch gait1992_description urdf_plus_fixed_tfs_skeleton.launch foot_left_name:=$FOOT_LEFT_NAME foot_right_name:=$FOOT_RIGHT_NAME use_gui:=${USE_GUI} tf_prefix:=$TF_PREFIX 
